### ISSUE TITLE
nb plugin命令安装提示插件不存在

### ISSUE THREAD

**Issue by avadiana** [fllesser/nonebot-plugin-parser#1]
您好，我在使用nb plugin install nonebot-plugin-resolver2命令安装时提示：root@osakaold:~/napcat/jubao# nb plugin install nonebot-plugin-resolver2
Package nonebot-plugin-resolver2 not found.

**Comment by fllesser** [comment]
换成下划线试试

**Comment by fllesser** [comment]
我试了一下-，_都行啊，你是什么时候安装的，这个插件今天才发到商店

**Comment by fllesser** [comment]
多运行几次试试，好像有点奇奇怪怪的问题

**Comment by fllesser** [comment]
> 您好，我在使用nb plugin install nonebot-plugin-resolver2命令安装时提示：root@osakaold:~/napcat/jubao# nb plugin install nonebot-plugin-resolver2
> Package nonebot-plugin-resolver2 not found.
> 

您好，请确保 nb-cli 为最新版，多试几次，插件是今天上架到商店的，cli 拉取商店列表会有缓存

**Comment by avadiana** [comment]
ok了，估计是下午那段时间商店缓存还没有更新，感谢哈

**Comment by fllesser** [comment]
> ok了，估计是下午那段时间商店缓存还没有更新，感谢哈

👌
