### ISSUE TITLE
能否修改b站视频下载的清晰度

### ISSUE THREAD

**Issue by ZhanYiLiangRan** [fllesser/nonebot-plugin-parser#19]
如题，默认下载好像是360p的清晰度
能调整成1080p或者720p之类的吗

**Comment by fllesser** [comment]
默认就是非大会员最高画质，配置哔哩cookie试试![Screenshot_20241228_113122_com.android.gallery3d_edit_469207742596110.jpg](https://github.com/user-attachments/assets/bfcbc626-5fb7-4246-be6a-94a7b82b130d)

**Comment by ZhanYiLiangRan** [comment]
> 默认就是非大会员最高画质，配置哔哩cookie试试![Screenshot_20241228_113122_com.android.gallery3d_edit_469207742596110.jpg](https://private-user-images.githubusercontent.com/64878354/399035546-bfcbc626-5fb7-4246-be6a-94a7b82b130d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNjQ1MTcsIm5iZiI6MTczNTM2NDIxNywicGF0aCI6Ii82NDg3ODM1NC8zOTkwMzU1NDYtYmZjYmM2MjYtNWZiNy00MjQ2LWJlNmEtOTRhN2I4MmIxMzBkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDA1MzY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YTMxZDc5YTRmNDZiZTllYWM1ZmY0NmVkODFkMmI1NDUxMjQ1NThlMTIwYjk0NmIyZWZlYjg2MjM4MjE2ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jeGpeE1oIjlt2aga8kmAVzO3PuxhVro2v3FJ6_ykDeM)
好的，感谢答复
