### ISSUE TITLE
windows下NotImplementedError与本插件无关

### ISSUE THREAD

**Issue by Tigrex-Dai** [fllesser/nonebot-plugin-parser#3]
![image](https://github.com/user-attachments/assets/fec6bb7c-2557-479c-85ca-aa28e355d54d)
![image](https://github.com/user-attachments/assets/fa277ad4-8d92-4c5d-95c2-5551c4b6b270)

**Comment by fllesser** [comment]
什么环境

**Comment by fllesser** [comment]
你这似乎不是我这个插件的报错

**Comment by Tigrex-Dai** [comment]
我是安装了插件以后报错的，卸载插件以后就一切正常了。
python3.10 llonebot

**Comment by fllesser** [comment]
> 我是安装了插件以后报错的，卸载插件以后就一切正常了。
> python3.10 llonebot

不可能的，我这个插件根本没用nonebot-plugin-htmlrender

**Comment by fllesser** [comment]
> 我是安装了插件以后报错的，卸载插件以后就一切正常了。
> 
> python3.10 llonebot

但是你这个看起来是nonebot-plugin-htmlrender的报错啊

**Comment by Tigrex-Dai** [comment]
好，那我去那里提个issue

**Comment by ElainaFanBoy** [comment]
> 好，那我去那里提个issue

请问一下您解决了吗，我也有相同的问题，是怎么解决的

**Comment by fllesser** [comment]
> > 好，那我去那里提个issue
> 
> 请问一下您解决了吗，我也有相同的问题，是怎么解决的

https://github.com/kexue-z/nonebot-plugin-htmlrender/issues/25
