### ISSUE TITLE
是否考虑添加对X多图动态的解析

### ISSUE THREAD

**Issue by ttlvip** [fllesser/nonebot-plugin-parser#8]
目前好像只能下载一条动态中的第一张图片。
例如链接：https://x.com/Gau1224/status/874549510310993921
![e960d1df679d4a0a77319ad4b1b72dd4](https://github.com/user-attachments/assets/01cef59b-fefb-450a-b7d5-d1a223f871cb)

**Comment by fllesser** [comment]
这个暂时支持不了，目前的方法只能解析出一张，如果你有方法，欢迎pr

**Comment by fllesser** [comment]
可以参考这个repo， https://github.com/caolvchong-top/twitter_download
